### ISSUE TITLE
Evaluate NIEM's use for privacy & sensitive information

### ISSUE THREAD

**Issue by markrdotson** [NIEM/NBAC-NTAC-collaboration#5]
Evaluate NIEM's use for privacy & sensitive information. Includes protected health information (PHI), HIPAA, 42 CFR, and FERPA (Federal Educational Rights and Privacy Act). Also issues of consent for use of data at run-time.

- [X] Get privacy markup schema from Brian Handspicker (PHI)
- [ ] NTAC to evaluate the provided PSM schemas as an input for privacy
- [ ] NTAC to review use cases from #2 when provided

**Comment by bdhandspicker** [comment]
Attached are Privacy Sensitivity Markup presentation and PSM IEPD zip file. They were originally created in 2012-2013 to capture "time-of-exchange" privacy requirements for medical, educational, criminal, financial, and other sensitive information associated with children in the NYS foster care and juvenile justice system. It is not a complete solution to the "just-in-time" authorization problem for previously exchanged sensitive information, since, for example, HIPAA consent may have been modified by a patient at the origin of the information or classification may have been updated for intelligence-protected information. But PSM may form a part of a broader NIEM privacy and security model.

From the schema comments:

        Privacy Sensitivity Marking (PSM) was developed by the New York 
        State (NYS) Information Technology Services (ITS) and the NYS Office 
        of Children and Family Services (OCFS) agencies to enable privacy
	sensitivity marking of documents, records, and elements for the purpose of 
        conforming with the information privacy marking and protection requirements
        of HIPAA, FERPA, Pediatric Medical Consent, Family Violence Indicators,
        and any other requirements for enabling protection of sensitive and private data.

        This Privacy Sensitivity Marking schema is modeled on the Intelligence 
        Community Information Security Marking (IC ISM) schema. IC-ISM was 
	chosen as the PSM model to leverage both the significant thought that has  
	been invested in IC-ISM over multiple decades and the investment in 
	implementation of IC-ISM as part of overall information sharing 
        policy and data standards framework of  the National Information
	Exchange Model (NIEM).

	This schema defines a Sensitivity Attribute Group to hold
        privacy sensitivity marking attributes which may then be associated
	with XML documents and elements via NIEM metadata link to a
	SensitivityAttributeGroup id. This allows variable level of granularity of the 
	privacy sensitivity marking from document-wide down to individual simple 
	elements and all resource portion levels between.

	The SensitivityAttributeGroup includes the following attributes:

		- sensitivity
		- steward
		- domain
		- program
		- dissemination
		- releasableTo
		- restrictedFrom
		- markedBy
		- markedDate
		- reason
		- derivedFrom
		- derivativelymarkedBy
		- expiryDate
		- expiryEvent
		- expiryException
   
Taken together sensitivity, steward, domain, and program attributes provide sufficient 
context for which very fine-grained privacy/sensitivity semantics can be inferred.
The dissemination, releasableTo, and restrictedFrom provide even finer explicit 
control over distribution and access authorization.

The markedBy, markedDate, reason, derivedFrom, and derivativelymarkedBy provide context 
and history that can help with the long-term maintenance decisions regarding individual markings.

Finally, the expiryDate, expiryEvent, and expiryException provide an opportunity for future 
automated "unprotection" of information.

I expect that few documents or records will make use of all the attributes in this group. If they 
have any privacy sensitivity marking at all, most documents will have the simplest attribute group, 
"sensitivity", "steward", and perhaps "markedBy". Yet the challenge with privacy sensitivity marking 
is that there are multiple different information domains, with different privacy and security requirements, 
and with some important edge use cases that must be satisfied. It is these edge cases that are likely 
to need the full flexibility of this Privacy Sensitivity Marking schema.

Brian Handspicker
bd@handspicker.net
413-672-8210

[Privacy Annotation Overview.pdf](https://github.com/NIEM/NBAC-NTAC-collaboration/files/2581106/Privacy.Annotation.Overview.pdf)
[PSM IEPD.zip](https://github.com/NIEM/NBAC-NTAC-collaboration/files/2581107/PSM.IEPD.zip)

**Comment by markrdotson** [comment]
CUI also added in 5.0 release
